# Use the official Nginx image from Docker Hub
FROM nginx:latest

# Copy custom Nginx configuration file to the container
COPY nginx.conf /etc/nginx/nginx.conf

# Copy static website files to the appropriate directory in the container
COPY html /usr/share/nginx/html

# Expose port 80 to allow access to the web server
EXPOSE 80

# Run Nginx in the foreground
CMD ["nginx", "-g", "daemon off;"]

